artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1gKzbHck3GnSFg1poogvL8X4c5soDmM-n/view
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion